---
archs:
  - ppc64le:
      distro: el8stream
  - x86_64:
      distro:
        - el8stream
        - el9stream:
            runtime-requirements:
              host_distro: newer
release_branches:
  master:
    - ovirt-master
